#!/bin/bash
# refresh-models.sh — Auto-detect latest models from CLI caches/sources
# Usage: bash agents/scripts/refresh-models.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MODELS_ENV="$SCRIPT_DIR/../models.env"
GEMINI_CLI_DIR="$HOME/.npm-global/node_modules/@google/gemini-cli"
GEMINI_SETTINGS="$HOME/.gemini/settings.json"
CODEX_CACHE="$HOME/.codex/models_cache.json"

echo "=== Detecting latest models ==="

# --- Codex: priority-0 from ~/.codex/models_cache.json ---
# Use cat | node (stdin) to avoid Windows path issues with node
CODEX_MODEL=""
CODEX_DATE_TMP=$(mktemp /tmp/codex_date_XXXXXX.txt)
if [ -f "$CODEX_CACHE" ]; then
  CODEX_MODEL=$(cat "$CODEX_CACHE" | node -e "
let d = '';
process.stdin.on('data', x => d += x);
process.stdin.on('end', () => {
  try {
    const data = JSON.parse(d);
    const m = data.models && data.models.find(x => x.priority === 0);
    const date = data.fetched_at ? '  [cache: ' + data.fetched_at.slice(0,10) + ']' : '';
    process.stderr.write(date);
    process.stdout.write(m ? m.slug : '');
  } catch(e) { process.stdout.write(''); }
});" 2>"$CODEX_DATE_TMP")

  if [ -n "$CODEX_MODEL" ]; then
    CACHE_DATE=$(cat "$CODEX_DATE_TMP" 2>/dev/null)
    echo "  Codex : $CODEX_MODEL$CACHE_DATE"
  else
    echo "  Codex : (parse failed, using fallback)"
  fi
else
  echo "  Codex : (no cache at ~/.codex/models_cache.json, using fallback)"
fi
rm -f "$CODEX_DATE_TMP"
CODEX_MODEL="${CODEX_MODEL:-gpt-5.3-codex}"

# --- Gemini: read from CLI core constants, check previewFeatures via bash ---
GEMINI_MODEL=""
if [ -d "$GEMINI_CLI_DIR" ]; then
  # Check previewFeatures in bash to avoid Windows path issues in node
  PREVIEW_ENABLED="false"
  if grep -q '"previewFeatures": true' "$GEMINI_SETTINGS" 2>/dev/null; then
    PREVIEW_ENABLED="true"
  fi

  GEMINI_MODEL=$(cd "$GEMINI_CLI_DIR" && PREVIEW="$PREVIEW_ENABLED" node --input-type=module -e "
import { PREVIEW_GEMINI_MODEL, DEFAULT_GEMINI_MODEL } from '@google/gemini-cli-core';
const preview = process.env.PREVIEW === 'true';
process.stdout.write(preview ? PREVIEW_GEMINI_MODEL : DEFAULT_GEMINI_MODEL);
" 2>/dev/null)

  if [ -n "$GEMINI_MODEL" ]; then
    echo "  Gemini: $GEMINI_MODEL  (previewFeatures=$PREVIEW_ENABLED)"
  else
    echo "  Gemini: (read failed, using fallback)"
  fi
else
  echo "  Gemini: (gemini-cli not found at $GEMINI_CLI_DIR, using fallback)"
fi
GEMINI_MODEL="${GEMINI_MODEL:-gemini-3-pro-preview}"

# --- Write models.env ---
cat > "$MODELS_ENV" << EOF
# Central model config — auto-generated by refresh-models.sh
# Last updated: $(date '+%Y-%m-%d %H:%M:%S')
# To refresh: bash agents/scripts/refresh-models.sh
CODEX_MODEL=${CODEX_MODEL}
GEMINI_MODEL=${GEMINI_MODEL}
EOF

echo ""
echo "Updated: agents/models.env"
echo "  CODEX_MODEL  = $CODEX_MODEL"
echo "  GEMINI_MODEL = $GEMINI_MODEL"
